### PR TITLE
had the app update daysLeft value daily

### PR DESCRIPTION
**Pull request by ExtremeSkepticist**
- had the app update daysLeft value daily

### CODE REVIEW

**Comment by Adamsmith6300** [comment]
You changed the function? Or you made the app call it daily from now on?

**Comment by ExtremeSkepticist** [comment]
The latter. The app subtracts daysLeft values of all food that some user
has daily except for food whose daysLeft has reached 0

2018년 5월 14일 (월) 오전 12:12, Adam <notifications@github.com>님이 작성:

**Comment by Adamsmith6300** [comment]
How are you doing it daily?

**Comment by ExtremeSkepticist** [comment]
Look at the changes on fridge.js

2018년 5월 14일 (월) 오전 12:15, Adam <notifications@github.com>님이 작성:

> How are you doing it daily?
>

**Comment by ExtremeSkepticist** [comment]
Last time i made a function called updateDaysLeft which subtracts all
food’s daysLeft value by 1 and displays the food data. I used the function.

On the get request routing for displaying user fridge, it retrieves
daysLeft & dayOut, expiry date of the food, from DB and then compares one
of the food’s daysLeft value to a value calculated with the expiry date &
todays date. If those are different, updateDaysLeft is invoked. If not, it
just displays user fridge.

2018년 5월 14일 (월) 오전 12:20, Adam <notifications@github.com>님이 작성:

> I see the changes but I don't quite see how that will run everyday?
>

**Pull request closed without merging**
